# Generated by Django 5.0.7 on 2024-07-16 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('text_body', models.CharField(max_length=250)),
                ('publish', models.DateTimeField(default=datetime.datetime(2024, 7, 16, 7, 48, 59, 125231, tzinfo=datetime.timezone.utc))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
